### ISSUE TITLE
XSD schema not consistent across branches

### ISSUE THREAD

**Issue by jongough** [OpenCPN/plugins#390]
I have just built testplugin for the latest versions of arch and done a validate against the beta schema , it fails with:
```
metadata/testplugin_pi-1.0.171.0-flatpak-aarch64-18.08-flatpak.xml:21: element target-arch: Schemas validity error : Element 'target-arch': [facet 'enumeration'] The value 'aarch64' is not an element of the set {'x86_64', 'armhf', 'arm64', 'noarch'}.
metadata/testplugin_pi-1.0.171.0-flatpak-aarch64-18.08-flatpak.xml fails to validate
metadata/testplugin_pi-1.0.171.0-flatpak-aarch64-20.08-flatpak-arm64.xml:21: element target-arch: Schemas validity error : Element 'target-arch': [facet 'enumeration'] The value 'aarch64' is not an element of the set {'x86_64', 'armhf', 'arm64', 'noarch'}.
metadata/testplugin_pi-1.0.171.0-flatpak-aarch64-20.08-flatpak-arm64.xml fails to validate
metadata/testplugin_pi-1.0.171.0-flatpak-aarch64-20.08-flatpak.xml:21: element target-arch: Schemas validity error : Element 'target-arch': [facet 'enumeration'] The value 'aarch64' is not an element of the set {'x86_64', 'armhf', 'arm64', 'noarch'}.
```
However, if I checkout the master branch and run the same validate against the same files it succeeds
```
All files pass xsd check

```
This suggests that the XSD schemas are not being maintained consistently when changes are being made. As the normal progress of releasing should be Alpha-Beta-Master it would appear that this progress is not being followed and changes are being made straight into Master. This then means testing of plugins is difficult as the non-master catalogs will not be up to date and any pushes made to them will be rejected.

**Comment by bdbcat** [comment]
Fixed...
Thanks for the catch
Dave

**Comment by jongough** [comment]
The alpha repository xsd is not consistent with the beta and prod versions. This makes testing difficult. I tried testplugin_pi with flatpak-aarch64 and it fails in alpha but not beta.

**Comment by bdbcat** [comment]
Corrected in Alpha now.

**Comment by rgleason** [comment]
Alpha branch should support meta urls as it did originally. This was an excellent idea that worked.  The plugin dev submitted a meta url and then simply added plugin meta date to his personnal branch and built an ocpn...xml file. That file was used.  No need to accept pr by bdbcat.

**Comment by rgleason** [comment]
I still find the meta-url entry in the ocpn-plugins.xml   so perhaps it is working. 

```
<plugin version="1">
    <name> Sean Depagnier Alpha Plugins meta-url </name>
    <version> 1.0 </version>
    <summary> meta-url to Sean's Alpha Plugins by rgleason </summary>
    <meta-url> https://raw.githubusercontent.com/rgleason/plugins/rg-alpha/ocpn-plugins.xml </meta-url>
  </plugin>

```

I regenerate a local ocpn-plugins.xml  as shown

```

Rick@Dart MINGW64 ~/documents/github/plugins (rg-alpha)
$ python tools/ocpn-metadata generate --userdir metadata --force
 Processing: metadata\ocpn-plugins.xml
 Processing: metadata\watchdog_pi-2.4.30.9-android-arm64-16-android-arm64.xml
 Processing: metadata\watchdog_pi-2.4.30.9-android-armhf-16-android-armhf.xml
 Processing: metadata\watchdog_pi-2.4.30.9-darwin-x86_64-10.14.4-macos.xml
 Processing: metadata\watchdog_pi-2.4.30.9-debian-x86_64-10-buster.xml
 Processing: metadata\watchdog_pi-2.4.30.9-flatpak-x86_64-18.08-flatpak-arm64.xml
 Processing: metadata\watchdog_pi-2.4.30.9-flatpak-x86_64-18.08-flatpak.xml
 Processing: metadata\watchdog_pi-2.4.30.9-mingw-x86_64-10-mingw.xml
 Processing: metadata\watchdog_pi-2.4.30.9-msvc-x86_64-10.0.14393-MSVC.xml
 Processing: metadata\watchdog_pi-2.4.30.9-raspbian-armhf-10.xml
 Processing: metadata\watchdog_pi-2.4.30.9-raspbian-armhf-9.13.xml
 Processing: metadata\watchdog_pi-2.4.30.9-ubuntu-x86_64-16.04-xenial.xml
 Processing: metadata\watchdog_pi-2.4.30.9-ubuntu-x86_64-18.04-bionic-gtk3.xml
 Processing: metadata\watchdog_pi-2.4.30.9-ubuntu-x86_64-18.04-bionic.xml
 Processing: metadata\watchdog_pi-2.4.30.9-ubuntu-x86_64-20.04-focal-gtk3.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-darwin-x86_64-10.14.4-macos.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-debian-x86_64-10-buster.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-flatpak-x86_64-18.08-flatpak-arm64.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-flatpak-x86_64-18.08-flatpak.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-mingw-x86_64-10-mingw.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-msvc-x86_64-10.0.14393-MSVC.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-ubuntu-x86_64-16.04-xenial.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-ubuntu-x86_64-18.04-bionic-gtk3.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-ubuntu-x86_64-18.04-bionic.xml
 Processing: metadata\weatherfax_pi-1.9.14.18-ubuntu-x86_64-20.04-focal-gtk3.xml
Generated new ocpn-plugins.xml at C:\Users\Rick\AppData\Local\ocpn-plugins.xml

```

In the Alpha Branch  metadata I still see the 3  meta-url files  
https://github.com/rgleason/plugins/tree/Alpha/metadata

**Comment by rgleason** [comment]
Perhaps I am not updating something correctly.

**Comment by rgleason** [comment]
Ok, I think meta-url works (if you use it properly).   Have found weatherfax 1.9.14.18 in the alpha branch  (downgrade) (the link does not work)

```
Rick@Dart MINGW64 ~/documents/github/plugins (rg-alpha)
$ git commit -am "update ocpn-plugins.xml + delete watchdog"  --no-verify
[rg-alpha 5f86254] update ocpn-plugins.xml + delete watchdog
 14 files changed, 269 insertions(+), 4176 deletions(-)
 delete mode 100644 metadata/ocpn-plugins.xml
 delete mode 100644 metadata/watchdog_pi-2.4.30.9-darwin-x86_64-10.14.4-macos.xml
 ..etc
 rewrite ocpn-plugins.xml (88%)

Rick@Dart MINGW64 ~/documents/github/plugins (rg-alpha)
$ git push origin rg-alpha
Enumerating objects: 7, done... remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/rgleason/plugins.git
   b111df3..5f86254  rg-alpha -> rg-alpha
```
